# Generated by Django 2.1 on 2019-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
