# Generated by Django 2.1 on 2019-04-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='d@gmail.com', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
