# Generated by Django 2.1 on 2019-04-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20190425_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='dinag707@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
