# Generated by Django 2.1 on 2019-04-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20190426_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectcomments',
            name='comment_reports',
        ),
        migrations.AddField(
            model_name='commentreports',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.ProjectComments'),
        ),
        migrations.AddField(
            model_name='commentreports',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='commentreports',
            unique_together={('user', 'comment')},
        ),
    ]
