# Generated by Django 2.1 on 2019-04-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20190425_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
